[tools]
node = "24.11.1"
python = "3.13.1"
rust = { version = "latest", targets = "aarch64-apple-darwin", components = "rust-src,clippy,rust-analyzer,llvm-tools" }
go = "1.25.4"
"npm:pnpm" = "10.26.1"
