model_reasoning_effort = "high"
approval_policy = "on-request"
sandbox_mode = "workspace-write"
hide_agent_reasoning = true
network_access = true

notify = ["/Users/shuntaka/dotfiles/home-manager/shared/scripts/notify.ts"]

web_search = "live"
suppress_unstable_features_warning = true
model = "gpt-5.3-codex"
personality = "pragmatic"
project_doc_fallback_filenames = ["CLAUDE.md"]

[features]
collaboration_modes = true

[projects."/Users/shuntaka/repos/github.com/shuntaka9576/memo"]
trust_level = "trusted"

[projects."/Users/shuntaka/dotfiles"]
trust_level = "trusted"
